behaviors:
  3DBall:
      trainer_type: ppo

      # hyperparameters:
      #   batch_size: 64
      #   beta: 0.001
      #   buffer_size: 12000
      #   epsilon: 0.2
      #   lambd: 0.99
      #   learning_rate: 0.0003
      #   learning_rate_schedule: linear
      #   max_steps: 5.0e5
      #   num_epoch: 3

      #   time_horizon: 1000
      #   sequence_length: 64
      #   summary_freq: 12000
      network_settings:
        num_layers: 2
        normalize: true
        hidden_units: 128
      reward_signals:
          extrinsic:
            strength: 1.0
            gamma: 0.99
      time_horizon: 1000
      sequence_length: 64
      summary_freq: 12000


